### ISSUE TITLE
0. Registration page, Self-assessment, School verification Form / Verification form

### ISSUE THREAD

**Issue by roboMoose** [slo-coders/tuber#28]

**Comment by o6nH** [comment]
Dependent on available topics
GET (/api/topics)
Display form
Form gets submitted
POST (/api/users/)
req = {userId:, firstName:, lastName: email:, password:, imageUrl:} 
// input file-type => form-data => blob => upload file
// validate(password) and hash(salt(password))
POST (/api/users/:userId/usertopics) UserTopic
req = topics : [{topicId: proficiencyRating:}, ...]
University verifies (‘Canvas LTI’, (code may not be necessary); email verifications)
