### ISSUE TITLE
2. Match form routes and Session Model

### ISSUE THREAD

**Issue by o6nH** [slo-coders/tuber#39]
Create Session model; with associations related to match form; and create routes that update (see below) 

If (Session.status !== ‘needToRate’) show form
2.1 Select user type
Set or update selectedUserType on UserSession table for current session
PUT (/api/sessions) Session
req = {(sessionId)?, userTypeSelected}

2.2 Select a course Topic (if mentee/peer) or Topics(mentor) 
PUT (/api/sessions) Session
req={(sessionId)?, currentSelectedCouseTopics: [topicIds, ...], status: 'waiting’} // for mentors/peers
req={(sessionId)?, currentSelectedCouseTopic: topicId, status: 'waiting’} // for mentees
2.3 Select preferred location from dropdown (for mentee) // TODO: allow location filtering NEXT in Version 2
PUT (/api/session) Session
ALWAYS IN FRONT OF THE LIBRARY!!!
SUBMIT REQUEST BUTTON (2.1 + 2.2)
DELETE REQUEST BUTTON 
PUT (/api/sessions) Session
req = {status: ‘unavailable’}
UPDATE TOPIC REQUEST
PUT (api/sessions)
req ={selectedCourseTopics: []} //mentors/peers
req ={selectedCourseTopic: ‘’} //mentee

**Comment by o6nH** [comment]
Session.courseTopicsSelected is an array (but an array of length 1 for mentees)

**Comment by roboMoose** [comment]
note: test at logout if status changes. Can only log out if rating has occurred. 
Still may need to store this info in a more permanent location (UserSession?)
