### ISSUE TITLE
Rating Algo

### ISSUE THREAD

**Issue by roboMoose** [slo-coders/tuber#65]
After meetup has ended - take proficiency score updated by partner on the UserMeetup session and combine with users running proficiency average for that topic.

Retrieve the most recent 30 UserMeetups for that topic, add the new score from the partner, get the average, and update the users UserTopic score.

**Comment by roboMoose** [comment]
to update a partners score: 
PUT /api/users/:userId/meetups/meetupId:

**Comment by o6nH** [comment]
not using the n most recent at this point since it would require we track the counts used and have a separate place to store the initial value (or store it will all others in UserMeetup somehow)
